nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs


packageExtensions:
  "next-intl@*":
    peerDependencies:
      next: "*"

unsafeHttpWhitelist:
  - "nexus.crepen.kro.kr"

npmScopes:
  crepen:
    npmRegistryServer: "https://nexus.crepen.kro.kr/repository/crepen-npm-group/"
    npmAlwaysAuth: true
    npmAuthIdent: "${CREPEN_NPM_AUTH_IDENT}"